services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`docker.test`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks: 
  default: # <-- Same network name as traefik yet different compose, results in test_default
    name: test_default
